#!/bin/bash
# First-time setup for bare-metal delaybox.
#
# Usage:
#   sudo ./bare-metal/setup.sh <earth-iface> <mars-iface>
#   sudo ./bare-metal/setup.sh                # uses .env at repo root
#
# Example:
#   sudo ./bare-metal/setup.sh enp1s0 enp2s0
#
# After running:
#   - .env is written at repo root (consumed by docker-compose.bare.yml)
#   - Docker images are built
#   - NICs are configured (promisc, offloads off) and the stack is started
#   - Dashboard at http://<this-host>:8080
#
# Re-running is safe: .env is overwritten with current args (or kept if
# invoked without args), images are rebuilt, NICs reconfigured, stack restarted.
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

# ── Argument / env handling ──────────────────────────────────────────────────
# Source existing .env first so VLAN IDs, delay settings, etc. are preserved
# across re-runs. Positional args (if any) then override EARTH_IFACE/MARS_IFACE.
if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
fi

if [ $# -ge 2 ]; then
    EARTH_IFACE="$1"
    MARS_IFACE="$2"
fi

if [ -z "$EARTH_IFACE" ] || [ -z "$MARS_IFACE" ]; then
    cat >&2 <<EOF
Usage: sudo $0 <earth-iface> <mars-iface>
       sudo $0    (after creating .env from bare-metal/.env.example)

EARTH_IFACE and MARS_IFACE must be provided as args or set in $ENV_FILE.
EOF
    exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must be run as root (use sudo)" >&2
    exit 1
fi

# ── Verify interfaces exist ──────────────────────────────────────────────────
for iface in "$EARTH_IFACE" "$MARS_IFACE" $MOON_SRC_IFACE $MOON_IFACE $CUSTOM_SRC_IFACE $CUSTOM_IFACE; do
    if ! ip link show "$iface" >/dev/null 2>&1; then
        echo "ERROR: interface '$iface' not found" >&2
        echo "Available interfaces:" >&2
        ip -br link show >&2
        exit 1
    fi
done

# ── Write .env for docker compose ────────────────────────────────────────────
{
    echo "# Generated by bare-metal/setup.sh on $(date -Iseconds)"
    echo "EARTH_IFACE=$EARTH_IFACE"
    echo "MARS_IFACE=$MARS_IFACE"
    [ -n "$EARTH_VLAN" ] && echo "EARTH_VLAN=$EARTH_VLAN"
    [ -n "$MARS_VLAN" ]  && echo "MARS_VLAN=$MARS_VLAN"
    [ -n "$MOON_SRC_IFACE" ] && echo "MOON_SRC_IFACE=$MOON_SRC_IFACE"
    [ -n "$MOON_IFACE" ]     && echo "MOON_IFACE=$MOON_IFACE"
    [ -n "$MOON_SRC_VLAN" ]  && echo "MOON_SRC_VLAN=$MOON_SRC_VLAN"
    [ -n "$MOON_VLAN" ]      && echo "MOON_VLAN=$MOON_VLAN"
    [ -n "$CUSTOM_SRC_IFACE" ] && echo "CUSTOM_SRC_IFACE=$CUSTOM_SRC_IFACE"
    [ -n "$CUSTOM_IFACE" ]     && echo "CUSTOM_IFACE=$CUSTOM_IFACE"
    [ -n "$CUSTOM_SRC_VLAN" ]  && echo "CUSTOM_SRC_VLAN=$CUSTOM_SRC_VLAN"
    [ -n "$CUSTOM_VLAN" ]      && echo "CUSTOM_VLAN=$CUSTOM_VLAN"
    [ -n "$EARTH_IP" ]       && echo "EARTH_IP=$EARTH_IP"
    [ -n "$EARTH_IP_MARS" ]  && echo "EARTH_IP_MARS=$EARTH_IP_MARS"
    [ -n "$EARTH_IP_MOON" ]  && echo "EARTH_IP_MOON=$EARTH_IP_MOON"
    [ -n "$MARS_IP" ]        && echo "MARS_IP=$MARS_IP"
    [ -n "$MOON_IP" ]        && echo "MOON_IP=$MOON_IP"
    [ -n "$CUSTOM_IP" ]      && echo "CUSTOM_IP=$CUSTOM_IP"
    [ -n "$MARS_LABEL" ]     && echo "MARS_LABEL=$MARS_LABEL"
    [ -n "$MOON_LABEL" ]     && echo "MOON_LABEL=$MOON_LABEL"
    [ -n "$CUSTOM_LABEL" ]   && echo "CUSTOM_LABEL=$CUSTOM_LABEL"
    [ -n "$HIDE_CUSTOM" ]    && echo "HIDE_CUSTOM=$HIDE_CUSTOM"
    [ -n "$DELAY_EARTH_TO_MARS" ]   && echo "DELAY_EARTH_TO_MARS=$DELAY_EARTH_TO_MARS"
    [ -n "$DELAY_MARS_TO_EARTH" ]   && echo "DELAY_MARS_TO_EARTH=$DELAY_MARS_TO_EARTH"
    [ -n "$DELAY_EARTH_TO_MOON" ]   && echo "DELAY_EARTH_TO_MOON=$DELAY_EARTH_TO_MOON"
    [ -n "$DELAY_MOON_TO_EARTH" ]   && echo "DELAY_MOON_TO_EARTH=$DELAY_MOON_TO_EARTH"
    [ -n "$DELAY_EARTH_TO_CUSTOM" ] && echo "DELAY_EARTH_TO_CUSTOM=$DELAY_EARTH_TO_CUSTOM"
    [ -n "$DELAY_CUSTOM_TO_EARTH" ] && echo "DELAY_CUSTOM_TO_EARTH=$DELAY_CUSTOM_TO_EARTH"
} > "$ENV_FILE"
echo "Wrote $ENV_FILE"

# ── Build images, then hand off to boot.sh for NIC config + up ──────────────
cd "$REPO_ROOT"
docker compose -f docker-compose.bare.yml build

"$REPO_ROOT/bare-metal/boot.sh"

IP=$(ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | head -1)
echo
echo "=== Delaybox running ==="
echo "  Earth ←→ ${EARTH_IFACE}${EARTH_VLAN:+ (VLAN $EARTH_VLAN)}    Mars ←→ ${MARS_IFACE}${MARS_VLAN:+ (VLAN $MARS_VLAN)}"
[ -n "$MOON_SRC_IFACE" ] && echo "  Earth ←→ ${MOON_SRC_IFACE}${MOON_SRC_VLAN:+ (VLAN $MOON_SRC_VLAN)}  Moon ←→ ${MOON_IFACE}${MOON_VLAN:+ (VLAN $MOON_VLAN)}"
[ -n "$CUSTOM_SRC_IFACE" ] && echo "  Earth ←→ ${CUSTOM_SRC_IFACE}${CUSTOM_SRC_VLAN:+ (VLAN $CUSTOM_SRC_VLAN)}  Custom ←→ ${CUSTOM_IFACE}${CUSTOM_VLAN:+ (VLAN $CUSTOM_VLAN)}"
echo
echo "Dashboard: http://${IP:-<host>}:8080"
echo "Logs:      docker compose -f docker-compose.bare.yml logs -f delaybox"
echo
echo "To start automatically on boot:"
echo "  sudo ./bare-metal/install-systemd.sh"
